name: Dev to master Workflow

on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test

      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push
