name: Feature to Dev CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies for backend
        run: |
          cd backend
          npm install --unsafe-perm=true
          chmod +x node_modules/.bin/jest

      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install --unsafe-perm=true

      - name: Run backend tests
        run: |
          cd backend
          npx jest

      - name: Run frontend tests
        run: |
          cd frontend
          npm test

      - name: Merge dev into main
        run: |
          git checkout main || git checkout -b main # Crée la branche si elle n'existe pas
          git merge dev
          git push origin main
